name: Inter-branch merge workflow
on:
  push:
    branches:
      - release/**

permissions:
  contents: write
  pull-requests: write

jobs:
  Merge:
    uses: f-alizada/arcade/.github/workflows/inter-branch-merge-base.yml@dev/f-alizada/longpath
    with:
      script_version: 'dev/f-alizada/longpath'
